remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: Rahul Chikkala
description: Research Intern | Software Engineer | MS Computer Science
show_downloads: false

# Site settings
author: Rahul Chikkala
email: rchikka1@binghamton.edu
url: https://rahul-chikkala.github.io
